export const emojiData = [
    { id: 1, emoji: "😀", name: "grinning face" },
    { id: 2, emoji: "😃", name: "grinning face with big eyes" },
    { id: 3, emoji: "😄", name: "grinning face with smiling eyes" },
    { id: 4, emoji: "😁", name: "beaming face with smiling eyes" },
    { id: 5, emoji: "😆", name: "grinning squinting face" },
    { id: 6, emoji: "😅", name: "grinning face with sweat" },
    { id: 7, emoji: "🤣", name: "rolling on the floor laughing" },
    { id: 8, emoji: "😂", name: "face with tears of joy" },
    { id: 9, emoji: "🙂", name: "slightly smiling face" },
    { id: 10, emoji: "🙃", name: "upside-down face" },
    { id: 11, emoji: "😉", name: "winking face" },
    { id: 12, emoji: "😊", name: "smiling face with smiling eyes" },
    { id: 13, emoji: "😇", name: "smiling face with halo" },
    { id: 14, emoji: "🥰", name: "smiling face with hearts" },
    { id: 15, emoji: "😍", name: "smiling face with heart-eyes" },
    { id: 16, emoji: "🤩", name: "star-struck" },
    { id: 17, emoji: "😘", name: "face blowing a kiss" },
    { id: 18, emoji: "😗", name: "kissing face" },
    { id: 19, emoji: "☺️", name: "smiling face" },
    { id: 20, emoji: "😚", name: "kissing face with closed eyes" },
    { id: 21, emoji: "😙", name: "kissing face with smiling eyes" },
    { id: 22, emoji: "🥲", name: "smiling face with tear" },
    { id: 23, emoji: "😋", name: "face savoring food" },
    { id: 24, emoji: "😛", name: "face with tongue" },
    { id: 25, emoji: "😜", name: "winking face with tongue" },
    { id: 26, emoji: "🤪", name: "zany face" },
    { id: 27, emoji: "😝", name: "squinting face with tongue" },
    { id: 28, emoji: "🤑", name: "money-mouth face" },
    { id: 29, emoji: "🤗", name: "hugging face" },
    { id: 30, emoji: "🤭", name: "face with hand over mouth" },
    { id: 31, emoji: "🤫", name: "shushing face" },
    { id: 32, emoji: "🤔", name: "thinking face" },
    { id: 33, emoji: "🤐", name: "zipper-mouth face" },
    { id: 34, emoji: "🤨", name: "face with raised eyebrow" },
    { id: 35, emoji: "😐", name: "neutral face" },
    { id: 36, emoji: "😑", name: "expressionless face" },
    { id: 37, emoji: "😶", name: "face without mouth" },
    { id: 38, emoji: "😏", name: "smirking face" },
    { id: 39, emoji: "😒", name: "unamused face" },
    { id: 40, emoji: "🙄", name: "face with rolling eyes" },
    { id: 41, emoji: "😬", name: "grimacing face" },
    { id: 42, emoji: "🤥", name: "lying face" },
    { id: 43, emoji: "😌", name: "relieved face" },
    { id: 44, emoji: "😔", name: "pensive face" },
    { id: 45, emoji: "😪", name: "sleepy face" },
    { id: 46, emoji: "🤤", name: "drooling face" },
    { id: 47, emoji: "😴", name: "sleeping face" },
    { id: 48, emoji: "😷", name: "face with medical mask" },
    { id: 49, emoji: "🤒", name: "face with thermometer" },
    { id: 50, emoji: "🤕", name: "face with head-bandage" },
    { id: 51, emoji: "🤢", name: "nauseated face" },
    { id: 52, emoji: "🤮", name: "face vomiting" },
    { id: 53, emoji: "🤧", name: "sneezing face" },
    { id: 54, emoji: "🥵", name: "hot face" },
    { id: 55, emoji: "🥶", name: "cold face" },
    { id: 56, emoji: "🥴", name: "woozy face" },
    { id: 57, emoji: "😵", name: "dizzy face" },
    { id: 58, emoji: "🤯", name: "exploding head" },
    { id: 59, emoji: "🤠", name: "cowboy hat face" },
    { id: 60, emoji: "🥳", name: "partying face" },
    { id: 61, emoji: "😎", name: "smiling face with sunglasses" },
    { id: 62, emoji: "🤓", name: "nerd face" },
    { id: 63, emoji: "🧐", name: "face with monocle" },
    { id: 64, emoji: "😕", name: "confused face" },
    { id: 65, emoji: "😟", name: "worried face" },
    { id: 66, emoji: "🙁", name: "slightly frowning face" },
    { id: 67, emoji: "☹️", name: "frowning face" },
    { id: 68, emoji: "😮", name: "face with open mouth" },
    { id: 69, emoji: "😯", name: "hushed face" },
    { id: 70, emoji: "😲", name: "astonished face" },
    { id: 71, emoji: "😳", name: "flushed face" },
    { id: 72, emoji: "🥺", name: "pleading face" },
    { id: 73, emoji: "😦", name: "frowning face with open mouth" },
    { id: 74, emoji: "😧", name: "anguished face" },
    { id: 75, emoji: "😨", name: "fearful face" },
    { id: 76, emoji: "😰", name: "anxious face with sweat" },
    { id: 77, emoji: "😥", name: "sad but relieved face" },
    { id: 78, emoji: "😢", name: "crying face" },
    { id: 79, emoji: "😭", name: "loudly crying face" },
    { id: 80, emoji: "😱", name: "face screaming in fear" },
    { id: 81, emoji: "😖", name: "confounded face" },
    { id: 82, emoji: "😣", name: "persevering face" },
    { id: 83, emoji: "😞", name: "disappointed face" },
    { id: 84, emoji: "😓", name: "downcast face with sweat" },
    { id: 85, emoji: "😩", name: "weary face" },
    { id: 86, emoji: "😫", name: "tired face" },
    { id: 87, emoji: "🥱", name: "yawning face" },
    { id: 88, emoji: "😤", name: "face with steam from nose" },
    { id: 89, emoji: "😡", name: "pouting face" },
    { id: 90, emoji: "😠", name: "angry face" },
    { id: 91, emoji: "🤬", name: "face with symbols on mouth" },
    { id: 92, emoji: "😈", name: "smiling face with horns" },
    { id: 93, emoji: "👿", name: "angry face with horns" },
    { id: 94, emoji: "💀", name: "skull" },
    { id: 95, emoji: "☠️", name: "skull and crossbones" },
    { id: 96, emoji: "💩", name: "pile of poo" },
    { id: 97, emoji: "🤡", name: "clown face" },
    { id: 98, emoji: "👹", name: "ogre" },
    { id: 99, emoji: "👺", name: "goblin" },
    { id: 100, emoji: "👻", name: "ghost" },
    { id: 101, emoji: "👽", name: "alien" },
    { id: 102, emoji: "👾", name: "alien monster" },
    { id: 103, emoji: "🤖", name: "robot" },
    { id: 104, emoji: "😺", name: "grinning cat" },
    { id: 105, emoji: "😸", name: "grinning cat with smiling eyes" },
    { id: 106, emoji: "😹", name: "cat with tears of joy" },
    { id: 107, emoji: "😻", name: "smiling cat with heart-eyes" },
    { id: 108, emoji: "😼", name: "cat with wry smile" },
    { id: 109, emoji: "😽", name: "kissing cat" },
    { id: 110, emoji: "🙀", name: "weary cat" },
    { id: 111, emoji: "😿", name: "crying cat" },
    { id: 112, emoji: "😾", name: "pouting cat" },
  ]
  
  